export default {
    probability: ["muito baixa", "baixa", "mediana", "alta", "muito alta", "desconhecido"],
    devsinindev: (displayName, placeId, probability, testerPing) => `\`👥\` desenvolvedores vistos no [${displayName}](<https://www.roblox.com/games/${placeId}>):\n-# probabilidade de atualizar atual: ${probability}\n-# ||<@&${testerPing}>||`,
    devsleft: (displayName, placeId, probability, testerPing) => `\`👥\` todos desenvolvedores vistos no [${displayName}](<https://www.roblox.com/games/${placeId}>) saíram\n-# probabilidade de atualizar atual: ${probability}\n-# ||<@&${testerPing}>||`,
    mainupdimg: (displayName, placeId, description, imageUrl, updatedTime, probability, mainUpdPing) => `# \`🚨\` [${displayName.toUpperCase()}](https://www.roblox.com/games/${placeId}) ATUALIZOU\n\`\`\`\n${description}\n\`\`\`\n[imagem](${imageUrl})\n-# há ${updatedTime}\n-# probabilidade de atualizar atual: ${probability}\n-# ||<@&${mainUpdPing}>||`,
    mainupd: (displayName, placeId, description, updatedTime, probability, mainUpdPing) => `# \`🚨\` [${displayName.toUpperCase()}](https://www.roblox.com/games/${placeId}) ATUALIZOU\n\`\`\`\n${description}\n\`\`\`\n-# há ${updatedTime}\n-# probabilidade de atualizar atual: ${probability}\n-# ||<@&${mainUpdPing}>||`,
    testupd: (displayName, placeId, updatedTime, testUpdPing) => `# \`🚨\` [${displayName.toUpperCase()}](<https://www.roblox.com/games/${placeId}>) ATUALIZOU\n-# há ${updatedTime}\n-# probabilidade de atualizar atual: ${probability}\n-# ||<@&${testUpdPing}>||`,
    newtopic: (preDisplay, username, topicSlug, topicId, createdAt, probability, topicsPing) => `\`📰\` novo tópico no devforum pel${preDisplay} ${username}: https://devforum.roblox.com/t/${topicSlug}/${topicId}\n-# há ${createdAt}\n-# probabilidade de atualizar atual: ${probability}\n-# ||<@&${topicsPing}>||`,
    joinedgame: (preDisplay, displayName, userId, lastLocation, placeId, lastStatus, lastStatusText, lastStatusBegin, probability, statusPing) => `\`🟢\` ${preDisplay} [${displayName}](<https://www.roblox.com/users/${userId}>) está jogando [${lastLocation}](https://www.roblox.com/games/${placeId})${lastStatus > 0 ? `\n-# ficou ${lastStatus == 2 ? `jogando ${lastLocation}` : lastStatusText} por ${lastStatusBegin}` : ""}\n-# probabilidade de atualizar atual: ${probability}\n-# ||<@&${statusPing}>||`,
    changedstatus: (statusEmoji, status, preDisplay, displayName, userId, lastStatus, lastStatusText, lastStatusBegin, presenceType, probability, studioPing, statusPing) => `\`${statusEmoji}\` ${preDisplay} [${displayName}](<https://www.roblox.com/users/${userId}>) está ${status}${lastStatus > 0 ? `\n-# ficou ${lastStatus == 2 ? `jogando ${lastStatus}` : lastStatusText} por ${lastStatusBegin}` : ""}\n-# probabilidade de atualizar atual: ${probability}\n-# ||<@&${presenceType == 3 ? studioPing : statusPing}>||`,
    embedFields: (testGameName, testLastUpdate, mainGameName, mainLastUpdate, statusEmoji, currentStatusText, currentStatusTime, lastStatusEmoji, lastStatusText, probability, nextChecks) => [
        { "name": `desenvolvedores no ${testGameName}`, "value": `\`👥\` ${nextChecks.testers.length}${nextChecks.testers.length > 0 ? " [(veja aqui)](https://discord.com/channels/1247404953073483877/1264712451572891678)" : ""}` },
        { "name": "últimas atualizações", "value": `\`${testGameName}\`  - <t:${testLastUpdate}>\n\`${mainGameName}\` - <t:${mainLastUpdate}>` },
        { "name": `status atual d${preDisplay} ${displayName}`, "value": `\`${statusEmoji}\` ${currentStatusText}${currentStatusTime ? ` (<t:${currentStatusTime}:R>)` : ""}` },
        { "name": `último status d${preDisplay} ${displayName}`, "value": lastStatusEmoji ? `\`${lastStatusEmoji}\` ${lastStatusText}` : "`❔` nenhum" },
        { "name": "probabilidade de atualizar atual", "value": probability },
        { "name": "próximas verificações", "value": `\`probabilidade\`: <t:${nextChecks.probability}:R>\n\`desenvolvedores no ${testGameName}\`: <t:${nextChecks.testers}:R>\n\`atualizações\`: <t:${nextChecks.updates}:R>\n\`tópicos\`: <t:${nextChecks.topics}:R>\n\`status\`: <t:${nextChecks.status}:R>` }
    ]
};